### ISSUE TITLE
How to change default video size?

### ISSUE THREAD

**Issue by dnuttall** [Digitalroot-Technologies/Html5VideoPlaylist#3]
I've been able to make the code work for a small prototype project (a karaoke machine), but my videos are 1920 X 1080 and look best in the 852 X 480 size.

How can I make that the default instead of the 640 X 480?

**Comment by Digitalroot** [comment]
https://github.com/Digitalroot/Html5VideoPlaylist/blob/master/css/main.css
line 39 and 40,
